package com.dzy.dao;

import com.dzy.model.CourseUserInfo;
import com.dzy.model.CourseUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_user_info
     *
     * @mbggenerated
     */
    int countByExample(CourseUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_user_info
     *
     * @mbggenerated
     */
    int deleteByExample(CourseUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_user_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_user_info
     *
     * @mbggenerated
     */
    int insert(CourseUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_user_info
     *
     * @mbggenerated
     */
    int insertSelective(CourseUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_user_info
     *
     * @mbggenerated
     */
    List<CourseUserInfo> selectByExample(CourseUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_user_info
     *
     * @mbggenerated
     */
    CourseUserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_user_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CourseUserInfo record, @Param("example") CourseUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_user_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CourseUserInfo record, @Param("example") CourseUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CourseUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CourseUserInfo record);
}